//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpBelot.Properties
{


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute( "Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0" )]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
	{

		private static Settings defaultInstance = ( ( Settings )( global::System.Configuration.ApplicationSettingsBase.Synchronized( new Settings() ) ) );

		public static Settings Default
		{
			get
			{
				return defaultInstance;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "CardsRes.dll" )]
		public string CardsDll
		{
			get
			{
				return ( ( string )( this[ "CardsDll" ] ) );
			}
			set
			{
				this[ "CardsDll" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "Коцето" )]
		public string SouthName
		{
			get
			{
				return ( ( string )( this[ "SouthName" ] ) );
			}
			set
			{
				this[ "SouthName" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "Пламка" )]
		public string NorthName
		{
			get
			{
				return ( ( string )( this[ "NorthName" ] ) );
			}
			set
			{
				this[ "NorthName" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "Хасан" )]
		public string EastName
		{
			get
			{
				return ( ( string )( this[ "EastName" ] ) );
			}
			set
			{
				this[ "EastName" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "Айше" )]
		public string WestName
		{
			get
			{
				return ( ( string )( this[ "WestName" ] ) );
			}
			set
			{
				this[ "WestName" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "True" )]
		public bool CapotRemovesDouble
		{
			get
			{
				return ( ( bool )( this[ "CapotRemovesDouble" ] ) );
			}
			set
			{
				this[ "CapotRemovesDouble" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "False" )]
		public bool ExtraPointsAreDoubled
		{
			get
			{
				return ( ( bool )( this[ "ExtraPointsAreDoubled" ] ) );
			}
			set
			{
				this[ "ExtraPointsAreDoubled" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "AIPlayers.dll" )]
		public string NorthDll
		{
			get
			{
				return ( ( string )( this[ "NorthDll" ] ) );
			}
			set
			{
				this[ "NorthDll" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "AIPlayers.dll" )]
		public string EastDll
		{
			get
			{
				return ( ( string )( this[ "EastDll" ] ) );
			}
			set
			{
				this[ "EastDll" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "AIPlayers.dll" )]
		public string WestDll
		{
			get
			{
				return ( ( string )( this[ "WestDll" ] ) );
			}
			set
			{
				this[ "WestDll" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "MISTRAL.TTF" )]
		public string MistralFontFile
		{
			get
			{
				return ( ( string )( this[ "MistralFontFile" ] ) );
			}
			set
			{
				this[ "MistralFontFile" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "CURLZ.TTF" )]
		public string CurlzFontFile
		{
			get
			{
				return ( ( string )( this[ "CurlzFontFile" ] ) );
			}
			set
			{
				this[ "CurlzFontFile" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "10" )]
		public int Speed
		{
			get
			{
				return ( ( int )( this[ "Speed" ] ) );
			}
			set
			{
				this[ "Speed" ] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute( "bg-BG" )]
		public string Culture
		{
			get
			{
				return ( ( string )( this[ "Culture" ] ) );
			}
			set
			{
				this[ "Culture" ] = value;
			}
		}
	}
}
