//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpBelot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpBelot.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All trumps.
        /// </summary>
        internal static string allTrumps {
            get {
                return ResourceManager.GetString("allTrumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  belot .
        /// </summary>
        internal static string belot {
            get {
                return ResourceManager.GetString("belot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        internal static string clubs {
            get {
                return ResourceManager.GetString("clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        internal static string congratulations {
            get {
                return ResourceManager.GetString("congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamonds.
        /// </summary>
        internal static string diamonds {
            get {
                return ResourceManager.GetString("diamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string doubled {
            get {
                return ResourceManager.GetString("doubled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  five in sequence .
        /// </summary>
        internal static string fiveSeq {
            get {
                return ResourceManager.GetString("fiveSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  four equal .
        /// </summary>
        internal static string fourEqual {
            get {
                return ResourceManager.GetString("fourEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  four in sequence .
        /// </summary>
        internal static string fourSeq {
            get {
                return ResourceManager.GetString("fourSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game of .
        /// </summary>
        internal static string gameOf {
            get {
                return ResourceManager.GetString("gameOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanging.
        /// </summary>
        internal static string hanging {
            get {
                return ResourceManager.GetString("hanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts.
        /// </summary>
        internal static string hearts {
            get {
                return ResourceManager.GetString("hearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last bid .
        /// </summary>
        internal static string lastBid {
            get {
                return ResourceManager.GetString("lastBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trumps.
        /// </summary>
        internal static string noTrumps {
            get {
                return ResourceManager.GetString("noTrumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redouble.
        /// </summary>
        internal static string redoubled {
            get {
                return ResourceManager.GetString("redoubled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  said by .
        /// </summary>
        internal static string saidBy {
            get {
                return ResourceManager.GetString("saidBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spades.
        /// </summary>
        internal static string spades {
            get {
                return ResourceManager.GetString("spades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  three in sequence .
        /// </summary>
        internal static string threeSeq {
            get {
                return ResourceManager.GetString("threeSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  won the game!!!.
        /// </summary>
        internal static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
    }
}
